### ISSUE TITLE
[Bug Report]: Item Book Enchantments applied improperly

### ISSUE THREAD

**Issue by Firestar311** [Crazy-Crew/Crazy-Envoys#112]
### Server Version

1.19.4

### Server Platform

Paper

### Describe the bug

Enchantments are applied in the wrong way on Enchanted Books
When applying enchantments to enchanted books, you need to use the [EnchantmentStorageMeta](https://jd.papermc.io/paper/1.20/org/bukkit/inventory/meta/EnchantmentStorageMeta.html) in order for the books to be able to be used in Anvils. 
I am a Sr Dev for a server and we discovered this from our players. I took a look at your code and figured that out
Also, Here are some NBT Screenshots of what is actually the problem
The first one here is taken from the vanilla creative mode and is what it should be: [Screenshot](https://gyazo.com/ace6b001eb8d3d0048cbeb278f0b083e)
This one here is what it actually looks like from this plugin: [Screenshot](https://gyazo.com/30ada433f0b95371a2a77bf07238b53b)
This is fine for normal items, but enchanted books need to be under the "StoredEnchantments" using the linked meta above

### Steps to reproduce

Have a tier with an item that has it set up like this: `'Item:Enchanted_Book, Mending:1, Amount:1'`
Start and envoy and find one with a book
Attempt to apply the book to an item in an anvil
See it not work

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
They aren't meant to be enchants that work in anvils, Use blacksmith to combine enchants.

https://docs.crazycrew.us/crazyenchantments/wiki/features#black-smith

**Comment by ryderbelserion** [comment]
I thought this was CrazyEnchantments for some reason
