### ISSUE TITLE
[Bug Report] Placeholders not wotking

### ISSUE THREAD

**Issue by Alexre** [Crazy-Crew/Crazy-Envoys#47]
**Describe the bug**
Placeholders don't work, I have placeholderapi installed.

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.8.8
 - Plugin Version: 1.3.10

*Do **NOT** say Latest use `/version crazyenvoy` in the console.

**Pastebin any errors in console**
-

**Issue**
-

**Screenshots**
-

**Comment by badbones69** [comment]
@Alexre could you show me a screenshot of your placeholder.

**Comment by Alexre** [comment]
> @Alexre could you show me a screenshot of your placeholder.

![image](https://user-images.githubusercontent.com/8046712/79071088-019cf600-7cda-11ea-817f-26f3e6d56173.png)

**Comment by Alexre** [comment]
Seems to work using {} placeholders, but they are only available on holographic displays, I can't get the papi placeholders to work on menus.

**Comment by RyderBelserion** [comment]
Fixed.
