### ISSUE TITLE
[Bug Report] Envoy Event

### ISSUE THREAD

**Issue by xbenzz** [Crazy-Crew/Crazy-Envoys#49]
**Describe the bug**
Listening on EnvoyStartEvent, all the API methods return empty. (spawnedLocations, etc)
Even event.isActive() returns false at EnvoyStartEvent

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.8.8
 - Plugin Version: 1.3.10

**Pastebin any errors in console**
None

**Issue**
API isn't working

**Screenshots**

**Comment by RyderBelserion** [comment]
Added to project tracker.
