### ISSUE TITLE
Crates are floating with default config

### ISSUE THREAD

**Issue by SpeedySapphire** [Crazy-Crew/Crazy-Envoys#52]
Crates are floating 5+ blocks above the ground sometimes with default config.

Version: https://gyazo.com/d4a1121423d780a0a6495d34b49c7151
Server Version: 1.8.9
Picture of the issue: https://cdn.discordapp.com/attachments/255937811428016130/720435452770779256/unknown.png
I have been asking in discord but I have not gotten a response.

**Comment by RyderBelserion** [comment]
Added to project tracker.
