### ISSUE TITLE
[Bug Report] No spawn locations were found and so the event has been cancelled and the cooldown has been reset.

### ISSUE THREAD

**Issue by demiena** [Crazy-Crew/Crazy-Envoys#54]
**Can't even use it**

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.12.2 Release
 - Plugin Version: 1.3.10 Update
 
*Do **NOT** say Latest use `/version crazyenvoy` in the console.

**Pastebin any errors in console**
Link: No errors are going on. the spawn location is just not working

**Issue**
Doing /envoy start just says No spawn locations were found and so the event has been cancelled and the cooldown has been reset.

**Screenshots**

**Comment by david73754** [comment]
same!

**Comment by david73754** [comment]
this happens on latest version, 1.12.2 release on my server, also not working.

**Comment by youdontknowmyname** [comment]
demiena said that demiena is running the latest version of the plugin, and demiena is running 1.12.2 release.

**Comment by txtrapline** [comment]
I have this issue as well.

**Comment by badbones69** [comment]
Did you guys set any spawn locations? If not you either need to set them with /envoy edit or you want to use a random spawn and set a center with /envoy center and enable the random spawns.

Random Spawn setting: https://github.com/Crazy-Crew/Crazy-Envoy/blob/4837db05ea5c5608321428a2f3c3489ba817b8d9/plugin/src/main/resources/config1.13-Up.yml#L11
