### ISSUE TITLE
[Bug Report] Crates are spawning underground!

### ISSUE THREAD

**Issue by AshuGuptaGamer** [Crazy-Crew/Crazy-Envoys#55]
**Describe the bug**
Whenever the CrazyEnvoy event starts the crates spawns below the ground instead of on top

**Versions (please complete the following information):**
 - Minecraft Server Version: [e.g. 1.16.3]
 - Plugin Version: [e.g. 1.3.11-Build#65]

**Screenshots**
![image](https://user-images.githubusercontent.com/59139918/96211779-d6e66f80-0f92-11eb-81ac-89e6cdb7d70f.png)

**Comment by RyderBelserion** [comment]
Added to project tracker.
