### ISSUE TITLE
[Bug Report] Random crate amount always picking max crates amount

### ISSUE THREAD

**Issue by Gfieldd** [Crazy-Crew/Crazy-Envoys#66]
**Describe the bug**
in config.yml the "Random amount: true" does not work, it still defaults to amount filled into "Max-Crates".
Toggling this to false has the exact same effect, changing "Min-Crates" does nothing, and "Max-Crates" just functions as the amount of crates spawning now

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.17.1
 - Plugin Version: 1.3.13-SNAPSHOT

**Pastebin any errors in console**
 no console errors

**Comment by RyderBelserion** [comment]
Added to our tracking board.
